export const UI_CORE_TEMPLATE = `# ui_core.verse - WidgetKit Base Module
# Download once and include in all generated WidgetKit files.
# Generated by WidgetKit - Epic Insight Engine

using { /Verse.org/Simulation }

event_subscription<public> := class:
    CancelEvent<public> : event() = event(){}
    Cancel<public>() : void =
        CancelEvent.Signal()

(Event : event(t) where t : type).Subscribe<public>(Callback(:t) : void) : event_subscription =
    Subscription := event_subscription{}
    spawn { AwaitForEvent(Event, Callback, Subscription) }
    return Subscription

AwaitForEvent<private>(
    Event        : event(t),
    Callback     : (:t) -> void,
    Subscription : event_subscription
    where t : type
)<suspends> : void =
    race:
        loop:
            Payload := Event.Await()
            Callback(Payload)
        Subscription.CancelEvent.Await()
`;
