import type { GeneratedOutput, ParsedWidget, VerseField } from "@/types/widgetkit";
import { UI_CORE_TEMPLATE } from "@/lib/widgetkit/ui-core-template";

function toSnakeCase(raw: string): string {
  return String(raw || "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function toPascalCase(raw: string): string {
  const normalized = String(raw || "")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim();
  if (!normalized) return "Field";

  return normalized
    .split(/\s+/)
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
    .join("");
}

function inferAssetParamType(field: VerseField): { paramType: string; needsTodo: boolean } {
  const ue5Class = String(field.ue5Class || "").toLowerCase();
  if (!ue5Class) return { paramType: "/* MaterialInstanceDynamic */", needsTodo: true };
  if (ue5Class.includes("material")) return { paramType: "material", needsTodo: false };
  if (ue5Class.includes("texture")) return { paramType: "texture", needsTodo: false };
  if (ue5Class.includes("widget")) return { paramType: "widget", needsTodo: false };
  return { paramType: "/* TODO: set concrete asset type */", needsTodo: true };
}

function fieldSetterSignature(field: VerseField): { paramType: string; body: string; needsTodoComment: boolean } {
  if (field.type === "Message") {
    return {
      paramType: "string",
      body: `set Widget.${field.name} = StringToMessage(Value)`,
      needsTodoComment: false,
    };
  }

  if (field.type === "Boolean") {
    return {
      paramType: "logic",
      body: `set Widget.${field.name} = Value`,
      needsTodoComment: false,
    };
  }

  if (field.type === "Floating") {
    return {
      paramType: "float",
      body: `set Widget.${field.name} = Value`,
      needsTodoComment: false,
    };
  }

  if (field.type === "Integer") {
    return {
      paramType: "int",
      body: `set Widget.${field.name} = Value`,
      needsTodoComment: false,
    };
  }

  const asset = inferAssetParamType(field);
  return {
    paramType: asset.paramType,
    body: `set Widget.${field.name} = Value`,
    needsTodoComment: asset.needsTodo,
  };
}

function renderSetterBlock(title: string, fields: VerseField[]): string {
  if (!fields.length) return "";

  const lines: string[] = [`    # -- Setters: ${title} --`];
  for (const field of fields) {
    const methodName = `Set${toPascalCase(field.name)}`;
    const signature = fieldSetterSignature(field);

    if (signature.needsTodoComment) {
      lines.push(`    # TODO: define a concrete type for asset field ${field.name}`);
    }

    lines.push(`    ${methodName}<public>(Value : ${signature.paramType}) : void =`);
    lines.push(`        ${signature.body}`);
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

export function generateVerseOutput(parsed: ParsedWidget): GeneratedOutput {
  const baseSnake = toSnakeCase(parsed.widgetName || "wdb_widget") || "wdb_widget";
  const widgetName = parsed.widgetName || "WDB_Widget";
  const uiClass = `${baseSnake}_ui`;
  const managerClass = `${baseSnake}_manager_device`;
  const managerFileName = `${baseSnake}_manager.verse`;

  const messages = parsed.fieldsByType.messages;
  const booleans = parsed.fieldsByType.booleans;
  const floats = parsed.fieldsByType.floats;
  const integers = parsed.fieldsByType.integers;
  const assets = parsed.fieldsByType.assets;
  const events = parsed.fieldsByType.events;

  const setterSections = [
    renderSetterBlock("Message", messages),
    renderSetterBlock("Boolean", booleans),
    renderSetterBlock("Floating", floats),
    renderSetterBlock("Integer", integers),
    renderSetterBlock("Asset", assets),
  ]
    .filter(Boolean)
    .join("\n\n");

  const eventHandlers = events.flatMap((field) => {
    const methodName = `On${toPascalCase(field.name)}`;
    return [
      `    ${methodName}<public>() : void =`,
      `        Print("[${widgetName}] ${methodName} triggered for {PlayerRef}")`,
      "        # TODO: add game logic",
      "",
    ];
  });

  const subscribeLines = events.map((field) => `        Widget.${field.name}.Subscribe(On${toPascalCase(field.name)})`);

  const mutableFields = [...messages, ...booleans, ...floats, ...integers, ...assets];
  const updateHelpers = mutableFields.flatMap((field) => {
    const helperName = `Update${toPascalCase(field.name)}`;
    const setterName = `Set${toPascalCase(field.name)}`;
    const paramType = fieldSetterSignature(field).paramType;

    return [
      `    ${helperName}<public>(Agent : agent, Value : ${paramType}) : void =`,
      `        if (UI := GetUI(Agent)?) { UI.${setterName}(Value) }`,
      "",
    ];
  });

  const managerCode = [
    "# Generated by WidgetKit - Epic Insight Engine",
    `# Widget: ${widgetName}`,
    "",
    "using { /Fortnite.com/Devices }",
    "using { /Fortnite.com/UI }",
    "using { /UnrealEngine.com/Temporary/UI }",
    "using { /UnrealEngine.com/Temporary/SpatialMath }",
    "using { /Verse.org/Simulation }",
    `# using { your/project/${widgetName} }`,
    "# using { your/project/ui_core }",
    "",
    "# -- UI Class --",
    `${uiClass}<public> := class:`,
    "    PlayerRef<public> : player",
    "    var Canvas<public> : canvas = canvas{}",
    `    var Widget<public> : ${widgetName} = ${widgetName}{}`,
    "",
    setterSections || "    # No mutable Verse fields found",
    "",
    "    # -- Event Handlers --",
    eventHandlers.length ? eventHandlers.join("\n").trimEnd() : "    # No events found",
    "",
    "    # -- Initialize --",
    "    Initialize<public>() : void =",
    "        set Canvas = canvas:",
    "            Slots := array:",
    "                canvas_slot:",
    "                    Anchors := anchors{",
    "                        Minimum := vector2{X := 0.5, Y := 0.5}",
    "                        Maximum := vector2{X := 0.5, Y := 0.5}",
    "                    }",
    "                    Alignment := vector2{X := 0.5, Y := 0.5}",
    "                    SizeToContent := true",
    "                    Widget := Widget",
    ...(subscribeLines.length ? subscribeLines : ["        # No event subscriptions"]),
    "",
    "# -- Manager Device --",
    `${managerClass}<public> := class(creative_device):`,
    `    var UIMap<private> : [player]?${uiClass} = map{}`,
    "",
    "    OnBegin<override>()<suspends> : void =",
    `        Print("[${widgetName} Manager] Ready")`,
    "",
    "    ShowUI<public>(Agent : agent) : void =",
    "        if:",
    "            Player := player[Agent]",
    "            PlayerUI := GetPlayerUI[Player]",
    "            not UIMap[Player]?",
    "        then:",
    `            UI := ${uiClass}{PlayerRef := Player}`,
    "            UI.Initialize()",
    "            PlayerUI.AddWidget(UI.Canvas, player_ui_slot{",
    "                InputMode := ui_input_mode.All",
    "                ZOrder := 1",
    "            })",
    "            if (set UIMap[Player] = option{UI}) {}",
    "",
    "    HideUI<public>(Agent : agent) : void =",
    "        if:",
    "            Player := player[Agent]",
    "            PlayerUI := GetPlayerUI[Player]",
    "            UI := UIMap[Player]?",
    "        then:",
    "            PlayerUI.RemoveWidget(UI.Canvas)",
    "            if (set UIMap[Player] = false) {}",
    "",
    `    GetUI<public>(Agent : agent) : ?${uiClass} =`,
    "        if (Player := player[Agent], UI := UIMap[Player]?) then option{UI} else false",
    "",
    "    # -- Update Helpers --",
    updateHelpers.length ? updateHelpers.join("\n").trimEnd() : "    # No update helpers generated",
  ]
    .filter(Boolean)
    .join("\n");

  return {
    managerFileName,
    managerCode,
    uiCoreCode: UI_CORE_TEMPLATE,
  };
}
